apiVersion: v1
kind: Pod
metadata:
  name: helloworld.db2dev.com
  labels:
    app: helloworld
spec:
  containers:
  - name: k8s-helloworld
    image: wardviaene/k8s-demo
    ports:
    - name: helloworld-port
      containerPort: 3000
    livenessProbe:
      httpGet:
        path: /
        port: 3000
      initialDelaySeconds: 15
      timeoutSeconds: 30
