apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld-controller
spec:
  replicas: 3
  selector:
    app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: k8s-helloworld
        image: wardviaene/k8s-demo
      ports:
      - name: helloworld-port
        containerPort: 3000
